name: magus
version: 0.0.2
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/magus
description: >
  Package for reading schema and making metadata available
dependencies:

# custom <magus dependencies>

  ini: ">=1.0.0<2.0.0"
  sqljocky: ">=0.11.0<0.12.0"
  ebisu: ">=0.0.12<0.0.13"

# end <magus dependencies>

dev_dependencies:
  yaml: "any"
  unittest: ">=0.11.0 < 0.12.0"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <magus dev dependencies>
# end <magus dev dependencies>

dependency_overrides:
# custom <magus dependency overrides>
# end <magus dependency overrides>

transformers:

# custom <magus transformers>
# end <magus transformers>

