name: magus
version: 0.0.12
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/magus
description: >
  Package for reading schema and making metadata available
dependencies:

# custom <magus dependencies>

  ini: ">=1.0.0<2.0.0"
  sqljocky: ">=0.11.0<0.12.0"
  ebisu: "^0.5.1"

# end <magus dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <magus dev dependencies>
  test: "^0.12.0"

environment:
  sdk: ">=1.8.0 <2.0.0"

# end <magus dev dependencies>

dependency_overrides:
# custom <magus dependency overrides>

#  ebisu:
#    path: /home/dbdavidson/dev/open_source/ebisu

# end <magus dependency overrides>

transformers:

# custom <magus transformers>
# end <magus transformers>

