name: magus
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:

# custom <magus dependencies>

  ini: ">=1.0.0"
  sqljocky: "any"

# end <magus dependencies>

dev_dependencies:
  unittest: ">=0.11.0"
  browser: "any"
  hop: ">=0.31.0"
  hop_docgen: ">=0.1.0 <0.2.0"

# custom <magus dev dependencies>
# end <magus dev dependencies>

transformers:

# custom <magus transformers>
# end <magus transformers>

